# Generated by Django 4.2.2 on 2023-07-23 15:20

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('postes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('postes', django.db.models.manager.Manager()),
            ],
        ),
    ]
